dist: bionic
language: php

php:
  - 7.3

cache:
  directories:
  - vendor
  - node_modules

notifications:
  email: false

before_install:
  - nvm install 12.16

install:
  - travis_retry composer self-update
  - COMPOSER_DISCARD_CHANGES=true travis_retry composer update --no-interaction --prefer-source
  - yarn

script:
  - phpunit --coverage-text --coverage-clover=coverage.xml

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
    - development
